# Generated by Django 3.0.4 on 2021-01-17 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='reco_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Reference_ID', models.CharField(max_length=150)),
                ('Receipt_No', models.CharField(max_length=150)),
                ('Order_ID', models.CharField(max_length=150)),
                ('Branch_name', models.CharField(max_length=150)),
                ('Branch_code', models.CharField(max_length=150)),
                ('Transaction_date', models.CharField(max_length=150)),
                ('Channel_Partner', models.CharField(max_length=150)),
                ('Amount', models.CharField(max_length=150)),
            ],
        ),
    ]
