# Generated by Django 3.0.4 on 2021-01-18 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_reco_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='merchant_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch_name', models.CharField(max_length=150)),
                ('branch_Code', models.CharField(max_length=150)),
                ('Business_Date', models.CharField(max_length=150)),
                ('ReceiptNo', models.CharField(max_length=150)),
                ('ReferenceID', models.CharField(max_length=150)),
                ('OrderId', models.CharField(max_length=150)),
                ('ProfitCenterType', models.CharField(max_length=150)),
                ('comments', models.CharField(max_length=150)),
                ('entry_date', models.CharField(max_length=150)),
                ('net_amount', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='transaction_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ID_No', models.CharField(max_length=150)),
                ('Order_ref_ID', models.CharField(max_length=150)),
                ('External_Platform_ID', models.CharField(max_length=150)),
                ('Channel', models.CharField(max_length=150)),
                ('Created_Date', models.CharField(max_length=150)),
                ('Order_State', models.CharField(max_length=150)),
                ('Request_Delivery_Time', models.CharField(max_length=150)),
                ('Time_Slot_Start', models.CharField(max_length=150)),
                ('Time_Slot_End', models.CharField(max_length=150)),
                ('Payment_Mode', models.CharField(max_length=150)),
                ('Payment_Transaction_ID', models.CharField(max_length=150)),
                ('Customer_Name', models.CharField(max_length=150)),
                ('Customer_ID', models.CharField(max_length=150)),
                ('Store_Name', models.CharField(max_length=150)),
                ('Store_ID', models.CharField(max_length=150)),
                ('Store_ref_ID', models.CharField(max_length=150)),
                ('Total_Amount', models.CharField(max_length=150)),
                ('Merchant_Total', models.CharField(max_length=150)),
                ('Sub_total_Amount', models.CharField(max_length=150)),
                ('Discount', models.CharField(max_length=150)),
                ('Aggregator_Discount', models.CharField(max_length=150)),
                ('Merchant_Discount', models.CharField(max_length=150)),
                ('Taxes', models.CharField(max_length=150)),
                ('Charges', models.CharField(max_length=150)),
                ('Fulfillment_mode', models.CharField(max_length=150)),
                ('Wallet_credit_amount', models.CharField(max_length=150)),
                ('City', models.CharField(max_length=150)),
            ],
        ),
    ]
