# Generated by Django 3.0.4 on 2021-01-19 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_merchant_data_transaction_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='reco_data',
            name='unmatched_data_count',
            field=models.CharField(default=4, max_length=150),
            preserve_default=False,
        ),
    ]
